---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-auth-route
  labels:
    appname: acmeair
spec:
  host: acmeair.apps.b3e14015.test.ocs
  path: /auth
  to:
    kind: Service
    name: acmeair-auth-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-auth-route-dr
  labels:
    appname: acmeair
spec:
  host: acmeair.apps.b3e14001.test.ocs
  path: /auth
  to:
    kind: Service
    name: acmeair-auth-service
