---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-main-route
  labels:
    appname: acmeair
spec:
  host: acmeair.apps.ocsm1301015.lnxero1.boe
  path: /acmeair
  to:
    kind: Service
    name: acmeair-main-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: acmeair-main-route-dr
  labels:
    appname: acmeair
spec:
  host: acmeair.apps.ocsm4204001.lnxero1.boe
  path: /acmeair
  to:
    kind: Service
    name: acmeair-main-service